### ISSUE TITLE
Prerender with standalone application don't work

### ISSUE THREAD

**Issue by oleksandr-pasko** [nestjs/ng-universal#1077]
steps to reproduce:
1. npx -p @angular/cli@latest ng new app --standalone
2. router: Yes
3. styles: css
4. cd app
5. npx -p @angular/cli@latest ng add @nestjs/ng-universal@latest
6. npm run prerender

Result: Unable to extract routes from application.
If manually change
 "import { AppServerModule } from '../src/main.server';" to "import bootstrap from '../src/main.server';"(app.module.ts) and 
"AngularUniversalModule.forRoot({
      bootstrap: AppServerModule," 
to 
" AngularUniversalModule.forRoot({
      bootstrap,". 
it will not solve issue.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
