### ISSUE TITLE
Can't resolve

### ISSUE THREAD

**Issue by eugenotop** [nestjs/ng-universal#11]
WARNING in ./node_modules/@nestjs/common/utils/load-package.util.js
Module not found: Error: Can't resolve '/src' in 'node_modules/@nestjs/common/utils'
 @ ./node_modules/@nestjs/common/utils/load-package.util.js
 @ ./node_modules/@nestjs/core/nest-factory.js
 @ ./node_modules/@nestjs/core/index.js
 @ ./apps/server/src/main.ts

ERROR in ./node_modules/@angular/core/fesm5/core.js
Module not found: Error: Can't resolve '/src' in '/node_modules/@angular/core/fesm5'
 @ ./node_modules/@angular/core/fesm5/core.js 18260:15-36 18272:15-102
 @ ./node_modules/@nguniversal/module-map-ngfactory-loader/fesm5/module-map-ngfactory-loader.js
 @ ./node_modules/@nestjs/ng-universal/dist/utils/setup-universal.utils.js
 @ ./node_modules/@nestjs/ng-universal/dist/angular-universal.providers.js
 @ ./node_modules/@nestjs/ng-universal/dist/angular-universal.module.js
 @ ./node_modules/@nestjs/ng-universal/dist/index.js
 @ ./node_modules/@nestjs/ng-universal/index.js
 @ ./apps/server/src/app/app.module.ts
 @ ./apps/server/src/main.ts

**Comment by eugenotop** [comment]
Resolve:
webpackConfigFactory.plugins = [new webpack.ContextReplacementPlugin(/angular(\\|\/)core(\\|\/)@angular/, path.resolve(__dirname, '../client/src'))];

**Comment by rcanessa89** [comment]
Is not working
