### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by niklasravnsborg** [nestjs/ng-universal#163]
Hi, I think I found a bug with this package. I can produce it with the following steps.

## Current behavior

After installing ng-universal into an existing project, I got the following error message:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/niklasravnsborg/Code/angular-nest-nebular/node_modules/intersection-observer/intersection-observer.js:724:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /Users/niklasravnsborg/Code/angular-nest-nebular/node_modules/@nebular/theme/bundles/theme.umd.js:2:469
    at Object.<anonymous> (/Users/niklasravnsborg/Code/angular-nest-nebular/node_modules/@nebular/theme/bundles/theme.umd.js:5:2)
[nodemon] app crashed - waiting for file changes before starting...
```

I suspect this has something to do with server side rendering but I don't get any error before installing `@nestjs/ng-universal`, so I would think this is a problem with this package.

## Minimal reproduction of the problem with instructions

```
ng new angular-nest-nebular
cd angular-nest-nebular
ng add @nebular/theme
ng add @nestjs/ng-universal
npm run serve
```

Or just clone the test repository and run `npm i && npm run server`:
https://github.com/niklasravnsborg/angular-nest-nebular

## Environment

Nest version: 6.0.0
@nestjs/ng-universal: 2.0.1
@nebular/theme: 4.4.0

**Comment by tayambamwanza** [comment]
Nebular is the issue, they are using the window object in theme.umd.js

**Comment by niklasravnsborg** [comment]
I see but why does the universal rendering work without any problem when you don’t use the Nest configuration?

**Comment by niklasravnsborg** [comment]
Thanks @tayambamwanza. Further discussion in https://github.com/akveo/nebular/issues/2008.

**Comment by danieldanielecki** [comment]
@tayambamwanza are you sure that's the issue? I could see you commenting in [#2008](https://github.com/akveo/nebular/issues/2008). I got the same problem after upgrading to `Angular 10` (from `Angular 8`)/`@nestjs/ng-universal 4.0.1` (from `@nestjs/ng-universal 1.2.0`). 

Basically, [applyDomino](https://github.com/nestjs/ng-universal/blob/master/lib/utils/domino.utils.ts) has stopped working, I have my [webpack.server.config.js](https://github.com/nestjs/ng-universal/issues/418#issuecomment-696933424) configuration to include `nodeExternals` with those packages which access the `window` object, but mocking using `applyDomino` seems not to have any effect anymore. Looks like there was some change with [bundle too](https://github.com/nestjs/ng-universal/issues/232#issuecomment-697170071), maybe that influence it. Trying with/without webpack, on `NestJS`/`Cloud Functions for Firebase` to host this and the same issue. Another idea is that it's somehow related to [change with builder in Angular CLI and how it builds & serves SSR apps](https://github.com/nestjs/ng-universal/issues/418#issuecomment-688170340).

I've seen that #429 has been immediately closed, but not sure if it should be the case.
