### ISSUE TITLE
Client app myapp not found

### ISSUE THREAD

**Issue by JeromeDesseaux** [nestjs/ng-universal#181]
Hi, 

Trying to install your package and getting "Client app myapp not found" while executing the given command inside my brand new angular app. 

Angular version : 8.2.14
Angular CLI : 8.3.20 

The command line result : 
```console
➜  ng-brigolo git:(master) ng add @nestjs/ng-universal --clientProject server    
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Client app server not found.
```

```console
➜  ng-brigolo git:(master) ✗ ng add @nestjs/ng-universal
Skipping installation: Package already installed
? What is the name of your application? server
Client app server not found.
```

**Comment by tanftw** [comment]
Your app name is prolly **ng-brigolo**. Please use that name instead.

**Comment by JeromeDesseaux** [comment]
It works. Thanks :) 

But what if I want to generate server related files in a specific folder ? Giving my current app name place them in the same folder..
