### ISSUE TITLE
Build failures in master

### ISSUE THREAD

**Issue by eternalmatt** [nestjs/ng-universal#189]
## I'm submitting a...

<pre><code>
[x] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Typescript cannot compile

## Expected behavior

Typescript compiles

## Minimal reproduction of the problem with instructions

`$ npm run build:schematics`

## What is the motivation / use case for changing the behavior?

I want the build to work so I can merge pull requests.

## Environment
For Tooling issues:
- Node version: 10.14.0
- Platform:  Windows

Others:
I tried bumping @types/node to latest, but this did not resolve the issue.  Sorry, I haven't investigate further than this.  I did notice that the merges on Nov 26 to master branch had failing commits as well (e.g. https://github.com/nestjs/ng-universal/commits/master)

**Comment by eternalmatt** [comment]
Interestingly, I went into `node_modules/@schematics/angular` and manually deleted `third_party` which contained duplicated and upsetting definitions for typescript.d.ts.   This gets the build to work.  Not sure where to take that.

**Comment by eternalmatt** [comment]
If you will downgrade @nestjs/ng-universal to use `typescript@3.5`, then the build succeeds.

psuedo compatibility chart until i'm told otherwise:

 typescript | @schematics/angular 
------|-----
3.4.3 | 8 
3.5 | 8.2
3.6.4 | 9

based upon: https://github.com/angular/angular-cli/commits/master/packages/schematics/angular/third_party/github.com/Microsoft/TypeScript

**Comment by kamilmysliwiec** [comment]
Just merged your PR. Thank you!

**Comment by eternalmatt** [comment]
Thanks for giving this attention!
