### ISSUE TITLE
Please publish new version to npm

### ISSUE THREAD

**Issue by eternalmatt** [nestjs/ng-universal#192]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request</code></pre>

## Current behavior

2.0.1 is latest (from four months ago)

## Expected behavior

3.0.0, or 2.1.0, or 2.0.2 is latest

## Minimal reproduction of the problem with instructions

https://www.npmjs.com/package/@nestjs/ng-universal

## What is the motivation / use case for changing the behavior?

I want the latest dependency changes from this module in my application.

## Environment
npm

**Comment by kamilmysliwiec** [comment]
2.0.1 https://github.com/nestjs/ng-universal/blob/master/package.json is the latest version. We'll publish 3.0.0 when Angular 9 is released

**Comment by eternalmatt** [comment]
Yeah, but I want it now.
