### ISSUE TITLE
Expose TypeScript Compiler in LiveReloadCompilerOptions

### ISSUE THREAD

**Issue by robertabramski** [nestjs/ng-universal#203]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Feature proposal
It would be useful to have the ability to override the TypeScript compiler used in `LiveReloadCompiler` for more flexibility in dev builds.

## What is the motivation / use case for changing the behavior?

TypeScript rather painfully does not natively support [absolute to relative path mapping](https://github.com/Microsoft/TypeScript/issues/15479), but with `ttypescript` and `ttsc`, it is possible to create builds that properly map the dependency paths.

I've implemented an enhancement directly in `serve-script.js` by copying the contents of `LiveReloadCompiler` and adapting the code to run outside of a TypeScript environment. It seems to do the trick for my use case. I would submit a PR, but I'm not very well-versed with all the tooling and package management surrounding submitting the enhancement.

```
const commands = [
  'ng build --aot --watch --delete-output-path=false',
  `${tsCompiler} --watch -p ${tsServerConfigFile}` // Change hard-coded compiler to option
];
```

## Environment
Running `serve-script.js` via `npm run serve`.
<pre><code>Nest version: 6.0.0</code></pre>

**Comment by kamilmysliwiec** [comment]
`LiveReloadCompiler` has been removed in the new major version. Angular 9 comes with a builder that ships live-reload out-of-the-box.
