### ISSUE TITLE
Angular 9: Do you HAVE to use Angular complier?

### ISSUE THREAD

**Issue by CWSpear** [nestjs/ng-universal#261]
## I'm submitting a...

<pre><code>[x] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request</code></pre>

## Current behavior
Because of the changes to Angular 9 and Ivy, you no longer include a pre-built bundle (i.e. `        bundle: require(join(process.cwd(), 'dist/universal/main')),`, but now are expected to import the server module directly (i.e. `bootstrap: AppServerModule`) and build your NestJS app with `@angular-devkit/build-angular:server` (which uses Webpack)... but that causes some problems, such as outlined in https://github.com/nestjs/ng-universal/issues/128 (issues with native modules, issues with dynamic loading of `typeorm` config and entities, etc).

## Expected behavior
You should still be able to build your NestJS server how ever you want (i.e. its own `tsconfig` and `tsc` and otherwise ran "bare metal") and still include Angular code for SSR.

## What is the motivation / use case for changing the behavior?
To support existing applications and to give more flexibility in our your server code is built and run.

## Environment

<pre><code>Nest version: 6.11.8

 
For Tooling issues:
- Node version: 12.16.1
- Platform:  Mac, Linux

Others:</code></pre>

**Comment by kamilmysliwiec** [comment]
Yes, it's required. I've reported an issue in Angular repo. Read more here https://github.com/angular/angular-cli/issues/16348

**Comment by CWSpear** [comment]
Dang, unfortunately that linked issue is closed even tho it didn't seem quite resolved...? (Or maybe I didn't understand it correctly?)

**Comment by kamilmysliwiec** [comment]
It seems that the `externalDependencies` option has been added https://github.com/angular/angular-cli/commit/0659cf09e3cba04b3f2770a03c660517a66ce380.
