### ISSUE TITLE
Can't use bcrypt in project.

### ISSUE THREAD

**Issue by CaptainKO** [nestjs/ng-universal#275]
Please help me, 
It worked fine until I import bcrypt library.

<pre><code>
ERROR in ./node_modules/node-pre-gyp/lib/unpublish.js
Module not found: Error: Can't resolve 'aws-sdk' in 'C:\Users\deoye\Documents\Angular\ourproduc\shoedee\node_modules\node-pre-gyp\lib'

ERROR in ./node_modules/node-pre-gyp/lib/publish.js
Module not found: Error: Can't resolve 'aws-sdk' in 'C:\Users\deoye\Documents\Angular\ourproduc\shoedee\node_modules\node-pre-gyp\lib'

ERROR in ./node_modules/node-pre-gyp/lib/info.js
Module not found: Error: Can't resolve 'aws-sdk' in 'C:\Users\deoye\Documents\Angular\ourproduc\shoedee\node_modules\node-pre-gyp\lib'
</code></pre>

Nest version:  ^6.0.0
 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Windows

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
