### ISSUE TITLE
Is rendering Angular SSR (Index page) from a NestJS Controller possible?

### ISSUE THREAD

**Issue by abbasogaji** [nestjs/ng-universal#362]
Am looking for a way to achieve;

```typescript

   @Post()
   @Render(<ANGULAR-SSR-PAGE>)
   renderPaymentPage(@Body bd){
        
    }
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
