### ISSUE TITLE
Support for multiple angular universal apps

### ISSUE THREAD

**Issue by ahaw** [nestjs/ng-universal#80]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Cannot host two universal apps. Routes are always redirected to last registered app:
<pre>
imports: [
		AngularUniversalModule.forRoot({
			viewsPath: DIST_BROWSER_FOLDER1,
			bundle: require(join(DIST_BRIDGE_FOLDER1, '/main.js')),
			renderPath: '/path1/*',
			liveReload: true,
		}),
		AngularUniversalModule.forRoot({
			viewsPath: DIST_BROWSER_FOLDER2,
			bundle: require(join(DIST_BRIDGE_FOLDER2, '/main.js')),
			renderPath: '/path2/*',
			liveReload: true,
		}),
	]
</pre>

## Expected behavior
We should be able to handle those two universal apps separatly. 

## What is the motivation / use case for changing the behavior?
Sometimes we might to host two angular universal app on one server. Without this feature we might need to have two nest servers to handle both of them

**Comment by alexisbmills** [comment]
It would be a very desirable feature. I have a universal app (website) that uses angular's i18n and we are building client/server bundles for each locale.

**Comment by ahaw** [comment]
I submitted PR for this issue (for now just for express)
https://github.com/nestjs/ng-universal/pull/164

**Comment by kamilmysliwiec** [comment]
We don't plan to add more features to this feature as it is supposed to be a tiny wrapper on top of `@nguniversal/express-engine`. If anyone needs more functionalities, we recommend forking this package and bringing it to the project's codebase.
