### ISSUE TITLE
TypeError: Class constructor Type cannot be invoked without 'new' - nest runtime error when using angular library + mikro orm

### ISSUE THREAD

**Issue by rat-matheson** [nestjs/ng-universal#842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Runtime error when running a nest app.  It appears to be related to mixing ES Modules with CommonJS modules but I am unable to deep dive to the point of resolving it on my own.

### Minimum reproduction code

https://github.com/rat-matheson/nest-mikro-bug/

### Steps to reproduce

I've created the following two repositories to demonstrate the issue.

- angular library - https://github.com/rat-matheson/nest-mikro-bug-lib/ 
- nest application - https://github.com/rat-matheson/nest-mikro-bug/
 

[transformType.ts](https://github.com/rat-matheson/nest-mikro-bug-lib/blob/main/projects/ngx-tmp/bug-repo/src/transformType.ts) is in a separate library package generated through the angular cli.  It is a simple implementation of the mikro orm [Type class](https://mikro-orm.io/docs/custom-types)

[app.service.ts](https://github.com/rat-matheson/nest-mikro-bug/blob/main/src/app.service.ts) is just a place in my nest application where I tried instantiating the class.

```
C:\Users\joelw\eclipse-workspace\tower-poi\packages\nest-bug-repo\projects\ngx-tmp\bug-repo\src\transformType.ts:3
export class TransformType<JsType = any, DbType = any> extends Type<JsType, DbType> {
^
TypeError: Class constructor Type cannot be invoked without 'new'
    at new TransformType (C:\Users\joelw\eclipse-workspace\tower-poi\packages\nest-bug-repo\projects\ngx-tmp\bug-repo\src\transformType.ts:3:1)
    at Function.TransformType.newTransform (C:\Users\joelw\eclipse-workspace\tower-poi\packages\nest-bug-repo\projects\ngx-tmp\bug-repo\src\transformType.ts:8:18)
    at Object.<anonymous> (C:\Users\joelw\eclipse-workspace\tower-poi\packages\nest-bug-repo\src\app.service.ts:5:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\joelw\eclipse-workspace\tower-poi\packages\nest-bug-repo\src\app.controller.ts:2:1)
```

### Expected behavior

The nest application should just start normally without throwing the runtime exception.  If I move transformType.ts to the nest project and just reference it there, everything starts fine.  So something is happening when the class is being packaged in a separate library and imported into the nest application.

I don't think the issue is really related to mikro orm as I've had similar problems trying to include other packages that did not involve mikro orm. 

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [x] Other (see below)

### Other package

@mikro-orm/core

### NestJS version

8.4.4

### Packages versions

[package.json for the nest application](https://github.com/rat-matheson/nest-mikro-bug/blob/main/package.json)
[package.json for the angular library](https://github.com/rat-matheson/nest-mikro-bug-lib/blob/main/package.json)

Angular info
```
Angular CLI: 12.2.17
Node: 16.13.2 (Unsupported)
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 12.2.16
... common, compiler, compiler-cli, core

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.17
@angular-devkit/build-angular   12.2.17
@angular-devkit/core            12.2.17
@angular-devkit/schematics      12.2.17
@angular/cli                    12.2.17
@schematics/angular             12.2.17
ng-packagr                      12.2.7
rxjs                            6.6.7
typescript                      4.3.5

```

Nest Info
```
[System Information]
OS Version     : Windows 10
NodeJS Version : v16.13.2
NPM Version    : 8.1.0

[Nest CLI]
Nest CLI Version : 8.2.5

[Nest Platform Information]
platform-express version : 8.4.4
schematics version       : 8.0.10
testing version          : 8.4.4
common version           : 8.4.4
core version             : 8.4.4
cli version              : 8.2.5
```

### Node.js version

v16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

If I upgrade to angular 13, it only produces .mjs files which I've also had issues incorporating into a nest app, so I'm sticking with angular 12 for the moment.  Although in this simple case, it seems a little strange for me to be using angular to create a library that extends Type, I have lots of libraries that are shared between the backend and front end and up until now, the angular cli has been great at managing them.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/ng-universal/issues/842#issuecomment-1118243358
